<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PostmanTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanTaskRepository extends EntityRepository
{
    public function delete(PostmanTaskInterface $postmanTask) {
        $em = $this->getEntityManager();
        $em->remove($postmanTask);
        $em->flush();
    }

    public function save(PostmanTaskInterface $postmanTask) {
        $em = $this->getEntityManager();
        $em->persist($postmanTask);
        $em->flush();
    }
}
