app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_Postman:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\PostmanController'
    name_prefix: api_1_ #naming collision